Assignment1/main.py
Assignment1/test.py

feat: check cmv condition 1, includes test

---

Assignment1/main.py
Assignment1/test.py

feat: check cmv condition 3, includes test

---

Assignment1/main.py
Assignment1/test.py

Closes #12 
Completes CMV condition 5 check,
Includes 4 tests for it, 1 positive, 2 negative and 1 wrong input

feat: added check for 5th CMV condition, includes 4 test cases

---

Assignment1/main.py
Assignment1/test.py

feat: check cmv condition 6, includes test

---

Assignment1/main.py
Assignment1/test.py

wrote the cmv condition 7 as well as tests for the condition. will need to refactor helper functions

Cmv condition 7

---

Assignment1/main.py
Assignment1/test.py

feat: added cmv condition 11

---

Assignment1/main.py
Assignment1/test.py

wrote cmv condition 12 and added tests

Cmv condition 12

---

Assignment1/main.py
Assignment1/test.py

Cmv condition nr 13

---

Assignment1/main.py
Assignment1/test.py

feat: added form_the_pum

---

Assignment1/README.md

feat: readme squeletton

---

Assignment1/main.py

fix: Added comments, make demo function use DECIDE

---

Assignment1/test_pum.py

fix: issue #49 test_pum.py now runs standalone

---

Assignment1/README.md

fix: added workflow to readme

---

Assignment1/README.md

Inserted instructions for running all unittests.
feat: issue #54

feat: adding instructions to run unittests

---

Assignment2/server.py

Closes #62 
…from github
added basic server that parses and prints to the terminal the user and email who pushed to the github repo

feat: issue #62 adding skeleton server that parses "push" webhooks

---

Assignment2/.gitignore
Assignment2/gitfunctions.py
Assignment2/server.py

Fixes #64 . 
However, we might want more functionality, the GitPython library is extensiiiive and I've spent a few hours experimenting with it so if you need help with it (or just want me to add more functionality) let me know. :) 
We can now git pull and checkout branches via Python.
The server does this automatically on push.
A new directory is created on your local file system for the repo.
That directory can be ignored.

feat: issue #64 added basic git functionality

---

Assignment2/build.py
Assignment2/gitfunctions.py
Assignment2/server.py

Close #67 
Now, after pulling the repo, syntax check will be conducted through pylint.

feat: issue #67 CI static syntax check on the project

---

Assignment2/.gitignore
Assignment2/gitfunctions.py
Assignment2/server.py
Assignment2/test_server.py

this is skeleton code that uses pytest to test flask web server functionality. run the test using "pytest test_server.py". requires pytest: "pip3 install pytest"
closes issue #75

feat: issue #75 create basic test case

---

Assignment2/server.py

fix: catch non push events issue #80

---

Assignment2/server.py

parsed ref to get branch name in order to clone branch where push was made
closes #82

feat: issue #82 clone specific branch

---

Assignment2/server.py

uses flask_mail (https://pythonhosted.org/Flask-Mail/) to create mail client, and send a test email
run "pip3 install Flask-Mail" to install flask_mail
under the deactivate function in env/bin/activate include the lines:
export USER2480="the_email"
export PASS2480="the_password"
in order to authenticate the sender
closes #78

feat: issue #78 implements basic email notification functionality

---

Assignment2/requirements.txt

created a requirements.txt for easier dependency installation using "pip3 install -r requirements.txt
closes #73

feat: issue #73 create requirements.txt for the server

---

Assignment2/gitfunctions.py
Assignment2/server.py
Assignment2/test.py
Assignment2/test_server.py

Issue 63 testing

---

Assignment2/server.py

changed email from my email to the web server email stored as environment variable locally
closes #88

fix: issue #88 change sender email for email notifications

---

Assignment2/requirements.txt

updated with 
flask_sqlalchemy 
flask_cors

chore: issue #92 update requirements.txt

---

Assignment2/readme.md
Assignment2/requirements.txt

added list of member's contributions

Add contributions, closes issue #95

---

Assignment2/readme.md

Explains how to start the browsable documentation for the project through pydoc.
Closes #99

feat: issue#99 explains how to start the browsable documentation

---

Assignment2/readme.md

by closing an ordered list. Also standardized headers in the readme
closes #108

issue #108 fixed indention in readme

---

Assignment2/readme.md
Assignment2/src/python/gitfunctions.py
Assignment2/src/python/server.py
Assignment2/src/test/test_server.py
Assignment2/start_server.py

Issue 118 update readme

---

Assignment2/src/python/server.py
Assignment2/src/test/test_server.py

fix: issue #121 fix boolean flag

---

Assignment2/src/python/gitfunctions.py

fix: issue #120 changed shutil function to onerror

---

Assignment2/src/python/server.py
Assignment2/src/test/test_server.py

fix: issue #127 fix unit tests

---

Assignment2/src/python/server.py
Assignment2/src/python/test.py
Assignment2/src/test/test_server.py

Issue 129 add build output

---

Assignment2/src/python/model.py
Assignment2/src/python/server.py
Assignment2/src/python/utils.py

issue #131 added database columns for output and error

---

Assignment2/src/python/server.py

Check the output of err and out

---

Assignment2/src/build-fe/src/components/ListItem.jsx
Assignment2/src/build-fe/src/pages/Home.jsx
Assignment2/src/python/server.py

issue #136 added build result to front end
